# -*- coding: utf-8 -*-
import json,csv
B="https://www.agenciarecria.com.br/"
# (arquivo, slug, campanha, titulo, texto principal, botao)
L=[
("01-calendario-conteudos","calendario-de-conteudos","ebooks","Calendário de 30 dias por R$ 5","Todo dia a mesma dúvida: \"o que eu posto hoje?\"\n\nMonte o seu calendário de conteúdos em 5 passos, com planilha pronta e banco de ideias, e chegue ao fim do mês com tudo planejado.\n\nRecria Calendário de Conteúdos: e-book por apenas R$ 5.\nToque em Saiba mais.","Saiba mais"),
("02-calendario-ia","calendario-com-ia","ebooks","Calendário com IA por R$ 8","E se a IA planejasse o seu mês de conteúdos?\n\nUm passo a passo para instruir a IA, mesmo na versão gratuita, e receber o seu calendário do mês planejado.\n\nRecria Calendário com IA: e-book por apenas R$ 8.\nToque em Saiba mais.","Saiba mais"),
("03-miv","miv","ebooks","Manual de identidade visual: R$ 15","O seu negócio tem manual de marca ou parece um Frankenstein, com tudo colorido sem que nada faça sentido?\n\nAprenda a desenvolver a sua identidade visual, com logo, tipografia, cores e posicionamento, e padronize as suas comunicações para deixar o negócio com aspecto mais profissional.\n\nRecria MIV: e-book por apenas R$ 15.","Saiba mais"),
("04-post","post","ebooks","Posts do mês em menos de 1 hora","Posts e carrosséis do mês, em menos de 1 hora?\n\nAprenda a criar as suas postagens com ferramentas gratuitas e IA, sem depender de designer.\n\nRecria Post: e-book por apenas R$ 10.\nToque em Saiba mais.","Saiba mais"),
("05-reels","reels","ebooks","Reels do mês em menos de 1 hora","Roteiros, legendas e edição dos seus Reels, em menos de 1 hora.\n\nAprenda a criar e editar os seus vídeos com ferramentas gratuitas e IA.\n\nRecria Reels: e-book por apenas R$ 12.\nToque em Saiba mais.","Saiba mais"),
("06-negocio-local","negocio-local","ebooks","Negócio local no digital: R$ 10","Você tem um negócio local? Que tal diversificar o seu faturamento no digital?\n\nNo e-book Negócio Local no Digital, você vai aprender várias formas de vender no digital e não depender só da venda física para ter caixa no seu negócio.\n\nApenas R$ 10. Toque em Saiba mais.","Saiba mais"),
("07-esteira","esteira-de-produtos","ebooks","Esteira de Produtos: R$ 12","Vender só um produto é deixar dinheiro na mesa.\n\nAprenda a criar a sua esteira de produtos, com produto de entrada, intermediário e premium, e diversifique as suas fontes de renda.\n\nE-book Esteira de Produtos, por apenas R$ 12.","Saiba mais"),
("08-low-ticket","100-ideias-low-ticket","ebooks","Mais de 100 ideias de low ticket","Ainda não tem um produto de entrada?\n\nSão mais de 100 ideias de produtos de baixo valor para pequenos, médios e grandes negócios, digitais e e-commerces, para você escolher o seu.\n\nE-book por apenas R$ 15. Toque em Saiba mais.","Saiba mais"),
("09-medium-ticket","medium-ticket","ebooks","Produto medium ticket: R$ 17","Você já tem o seu produto de entrada? Está na hora do intermediário.\n\nAprenda a desenvolver o seu produto medium ticket e faça quem comprou um produto mais barato comprar de você um produto de maior valor agregado, aumentando o seu LTV.\n\nE-book por apenas R$ 17.","Saiba mais"),
("10-high-ticket","high-ticket","ebooks","Produto high ticket: R$ 27","Já vende produto de entrada e intermediário? Está na hora do premium.\n\nDesenvolva o seu high ticket da melhor forma e analise qual é o momento certo de ativá-lo, sem queimar audiência e sem queimar dinheiro em tráfego pago.\n\nE-book por apenas R$ 27.","Saiba mais"),
("11-estrutura-negocio","estrutura-de-negocio","ebooks","Manual de Estrutura de Negócio","O seu negócio depende só de você?\n\nOrganize a base do negócio para ele funcionar com mais clareza e sustentar o crescimento, seja você um negócio local, um profissional ou um negócio digital.\n\nManual por apenas R$ 37. Toque em Saiba mais.","Saiba mais"),
("12-express","estrategia-express","cursos","Curso Express por R$ 15","A estratégia por trás dos meus produtos de baixo ticket, em um curso rápido e direto.\n\nAprenda a estratégia atraente que vende, por apenas R$ 15.\n\nToque em Saiba mais.","Saiba mais"),
("13-manual-narrativas","manual","ebooks","Manual de Narrativas: R$ 47","Vender sem lives, sem lançamentos e sem postar todo dia.\n\nO Manual de Narrativas Atraentes Que Vendem mostra como contar boas histórias que vendem.\n\nE-book por apenas R$ 47. Toque em Saiba mais.","Saiba mais"),
("14-recria-ads","recria-ads","cursos","Recria Ads: anúncio sem cara de anúncio","Hoje, a grande maioria das pessoas pula anúncio, inclusive você. Mas todo mundo para pra ouvir uma boa história.\n\nAprenda a criar conteúdos e anúncios sem cara de anúncio, sem parecer aquele vendedor chato, mesmo com pouco orçamento, a partir de 10 minutos por dia.\n\nCurso Recria Ads: R$ 97 ou parcele em 12x.","Saiba mais"),
("15-comunidade","comunidade-recria-business","cursos","Comunidade Recria Business","Você é a soma das 5 pessoas mais próximas de você. Como isso impacta o seu negócio?\n\nSe você tem um negócio, precisa estar imerso num ambiente com outros empreendedores para ter novos insights e continuar se recriando.\n\nParticipe da comunidade Recria Business: conteúdos de marketing, negócio, posicionamento, anúncios, comercial e IA, com lives e mentorias em grupo. Plano mensal ou anual.","Saiba mais"),
("16-diagnostico","diagnostico-recria","servicos","Diagnóstico Recria por R$ 67","1 hora para descobrir o que trava o seu negócio.\n\nUma consultoria individual, online, para enxergar com clareza o seu próximo passo.\n\nDiagnóstico Recria: R$ 67. Toque em Saiba mais.","Saiba mais"),
("17-pacote-inicial","pacote-mkt-inicial","servicos","Pacote inicial de marketing","Toda a estrutura mínima de marketing para vender mais, por um valor acessível.\n\nTráfego pago, social media, treinamento do time comercial e site (para quem fica no mínimo 3 meses), em um só pacote.\n\nPacote inicial: R$ 1.500 por mês.","Saiba mais"),
("18-mentoria","mentoria-recria","servicos","Mentoria Recria","Você está com vários gargalos no negócio e nem sabe como resolver?\n\nSeja crescimento, aumento de faturamento, operacional ou diversificação: na mentoria da Recria, eu pego na sua mão e te ajudo a arrumar cada gargalo de marketing, negócio e comercial.\n\nToque em Saiba mais.","Saiba mais"),
("19-empresa-100","recria-eupresa","eupresa","Anúncios a partir de R$ 100","Você é uma EUpresa ou microempresa? Conheça o Recria EUpresa.\n\nFazemos o anúncio para o seu negócio a partir de R$ 100 de gestão por semana. Salão de beleza, manicure, prestador de serviço, negócio local ou pequeno: cuidamos do seu tráfego por um orçamento acessível, para você aumentar a sua base de clientes.\n\nSem contrato. Toque em Saiba mais.","Saiba mais"),
("20-empresa-beleza","recria-eupresa","eupresa","Anuncie sem contrato","Salão, manicure, loja pequena: anuncie sem contrato.\n\nComece com 1 semana: você paga, a gente trabalha por 7 dias e entrega o relatório com os dados da campanha.\n\nGestão a partir de R$ 100, mais a verba de anúncio de R$ 50 a R$ 100 por semana, paga no Instagram.","Saiba mais"),
("21-empresa-mes","recria-eupresa","eupresa","30 dias de anúncios por R$ 400","30 dias de anúncios cuidados por quem entende.\n\nR$ 400 de gestão no mês, mais a verba de anúncio de R$ 50 a R$ 100 por semana, paga no Instagram. Sem contrato.\n\nToque em Saiba mais e veja o plano.","Saiba mais"),
("22-servicos","","servicos","Agência de tráfego pago","Cuidamos do marketing do seu negócio com uma estratégia baseada em neurociência e psicologia do consumidor.\n\nSeja com tráfego pago, social media, consultoria, treinamentos, estruturação de negócio... Somos uma agência que estuda a fundo como funciona a mente humana e usa isso a favor do seu negócio para você vender mais.\n\nPeça o seu orçamento.","Saiba mais"),
("23-checklist-instagram","checklist-instagram","iscas","Checklist do Instagram, grátis","O seu Instagram está vendendo ou só ocupando espaço?\n\nEm 20 minutos, descubra o que melhorar no seu perfil: foto, bio, destaques, feed e conteúdo.\n\nBaixe grátis o Checklist de Revisão do Instagram.","Cadastre-se"),
("24-aulao","aula-mkt-para-negocios","iscas","Aula gratuita: marketing e vendas","Por que o seu marketing não funciona e o seu comercial não converte?\n\nUma aula gratuita, com mais de 10 anos de experiência em marketing e comercial, para você enxergar o que está travando as suas vendas.\n\nToque em Saiba mais.","Saiba mais"),
("25-grupo-recriadores","recriadores-wapp","iscas","Comunidade gratuita Recriadores","Entre na comunidade gratuita Recriadores.\n\nConteúdos exclusivos sobre negócio, marketing e vendas, direto no seu WhatsApp, toda semana.\n\nToque em Saiba mais e entre.","Saiba mais"),
]
rows=[]
md=["# Anúncios Recria · legendas e links (Meta Ads)\n","Cada criativo tem 2 versões em PNG: `feed-1x1/` (1080x1080) e `stories-9x16/` (1080x1920, com as margens de segurança de Stories/Reels). Campos para o Gerenciador de Anúncios:\n","- **Texto principal**: a legenda do anúncio (os primeiros ~125 caracteres aparecem antes de \"ver mais\").\n- **Título**: o título curto, abaixo da imagem.\n- **Botão**: botão de chamada para ação.\n- **URL**: o link de destino, já com UTM (origem `instagram_ads`).\n- **Nome do anúncio**: use o nome do arquivo.\n","---\n"]
for f,slug,camp,tit,txt,btn in L:
    url=B+(slug+"/" if slug else "")+f"?utm_source=instagram_ads&utm_medium=cpc&utm_campaign={camp}&utm_content={f}"
    rows.append([f,tit,txt.replace("\n"," | "),btn,url])
    md.append(f"## {f}\n\n**Título:** {tit}\n\n**Botão:** {btn}\n\n**URL:** {url}\n\n**Texto principal:**\n\n"+"\n".join("> "+l if l else ">" for l in txt.split("\n"))+"\n\n---\n")
open('legendas-anuncios.md','w',encoding='utf-8').write("\n".join(md))
with open('legendas-anuncios.csv','w',encoding='utf-8-sig',newline='') as fh:
    w=csv.writer(fh,delimiter=';');w.writerow(['Nome do anúncio','Título','Texto principal','Botão','URL de destino']);w.writerows(rows)
print(len(L))
